# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dcb12b41561862a1cb08f0e6c0537c371b57794e143650a0cc62efc3871519f398c7b3ccfc6660dd4bec72415268a8f76ae100787fd4455ed8aaf9d4b73e9d6

test:
  secret_key_base: 6f6f70c032141f261193e35e441df7e40da37cb1dc75074567dc7926f05177baf902cf3c541da3feb409e4a8372b128da2979fb45740603869bbffa5853dceb7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
